" default options
set backspace=indent,eol,start
set title
set ruler
set hidden
set incsearch
set laststatus=2
set modelines=5
set ignorecase
set scrolloff=10
set shiftwidth=4
set showcmd
set showmatch
set showmode
set smartcase
set tabstop=4
set wildmode=longest,list,full
set wildmenu
set nofoldenable
